[package]
name = "snake"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[workspace]
resolver = "2" # Important! wgpu/Bevy needs this!
